Squashed commit of the following:
commit 0b71a2c09454ac1034b58ecc427286e6bc4c9776
Author: Max Strasinsky <98811342+mstrasinskis@users.noreply.github.com>
Date:   Wed May 22 09:11:39 2024 +0200

    Select universe card all actionable mode (#4901)

    # Motivation

    For select "all actionable proposals" we need to have a universe card
    with the "Vote" icon and static text. To maintain the original universe
    card’s styles and functionality, we extended the existing
    SelectUniverseCard component rather than creating a new one.

    # Changes

    - Extend `SelectUniverseCard` to display a "Actionable proposals" card.

    # Tests

    - Extended.

    <img width="273" alt="image"
    src="https://github.com/dfinity/nns-dapp/assets/98811342/11e4e564-9e47-4c39-8e2f-f4e35b2be067">

    # Todos

    - [ ] Add entry to changelog (if necessary).
    Not yet.

commit ed2f186618cfab197e2e12083fafdcb2455ba390
Author: David de Kloet <122978264+dskloetd@users.noreply.github.com>
Date:   Tue May 21 19:40:38 2024 +0200

    NNS1-2905: Remove transactions fields from accounts (step 2) (#4836)

    This PR should only be merged after we have a release on mainnet
    containing https://github.com/dfinity/nns-dapp/pull/4800.

    The commit currently on mainnet:
    ```
    $ dfx canister metadata nns-dapp git_commit_id --network mainnet
    581eb325ce38d98f3e6e9c13ab2e490701ca91c3
    ```
    That
    [commit](https://github.com/dfinity/nns-dapp/commit/581eb325ce38d98f3e6e9c13ab2e490701ca91c3)
    is from May 15th, well after PR #4800, which was merged May 10th.

    # Motivation

    This is the follow-up to https://github.com/dfinity/nns-dapp/pull/4800.
    In the previous PR we removed the transactions fields but still encoded
    to stable memory including the fields.
    In this PR we stop encoding the old fields completely.
    There will still be accounts in stable memory with the fields but they
    will be ignored when reading and removed when writing.
    We have not yet decided if we also want to do a migration round to
    remove all the fields from stable memory.

    # Changes

    1. Stop converting `Account` to `OldAccount` before encoding it to
    stable memory.

    # Tests

    1. `upgrade-downgrade-test` passed.
    2. Manually tested upgrading and downgrading while creating new
    subaccounts before, in between and after.

    # Todos

    - [x] Add entry to changelog (if necessary).

commit 7a9f74e10bf38df2a2e6ef3751c3a9eabe05684e
Author: Max Strasinsky <98811342+mstrasinskis@users.noreply.github.com>
Date:   Tue May 21 17:31:10 2024 +0200

    Upgrade gix components (#4898)

    # Motivation

    For the actionable page menu entry, we need an updated `Vote` icon with
    size prop support.

    # Changes

    - `npm run update:gix`

    # Tests

    Tests work.

    # Todos

    - [ ] Add entry to changelog (if necessary).
    Not necessary.

commit 913811892f210ee729bdee95ab2d9b4580623771
Author: David de Kloet <122978264+dskloetd@users.noreply.github.com>
Date:   Tue May 21 16:26:25 2024 +0200

    Prevent installing a second snapshot before the previous one is restored (#4900)

    # Motivation

    When installing a snapshot, some files and directories are replaced with
    ones from the snapshot and the originals are placed in a backup
    directory.
    If you try to install a snapshot again, things can get confusing easily.
    Better to always restore the previous backup before installing the next.

    # Changes

    In `scripts/dfx-snapshot-install`, check if there is a directory with a
    name following the standard state backup directory name pattern. If
    there is, refuse to install the snapshot.

    # Tests

    Manually created a directory named `dfx-state-backup-123` and then tried
    to run a snapshot. Got:
    ```
    $ scripts/dfx-snapshot-start -s /Users/dskloet/snapshots/2024-05-16-ckUSDC.tar.xz
    drwxr-xr-x  2 dskloet  staff  64 May 21 15:12 /Users/dskloet/dfx-state-backup-123
    ERROR: Found existing backup directory. Restore the previous backup before installing a new snapshot.
    sh: /Users/dskloet/dfx-state-backup-20240521_152046/restore.sh: No such file or directory
    ```

    # Todos

    - [ ] Add entry to changelog (if necessary).
    not necessary

commit ead5b231384cf8a07b86040abcd9184ae00dab95
Author: David de Kloet <122978264+dskloetd@users.noreply.github.com>
Date:   Tue May 21 16:12:50 2024 +0200

    Keep existing identities when installing snapshot (#4899)

    # Motivation

    When installing an snsdemo snapshot, the entire `~/.config/dfx`
    directory gets replaced with the one from the snapshot.
    This includes all your identities.
    So while a snapshot is running, you can't use your normal identities.

    # Changes

    Instead of replacing the entire `~/.config/dfx` directory, replace all
    its contents (according to the snapshot), except the `identity`
    directory, then replace only those identities that exist in the
    snapshot, keeping the others.

    # Tests

    Ran a snapshot. Checked that identities were still there.

    # Todos

    - [ ] Add entry to changelog (if necessary).