Update sns_aggregator IC cargo dependencies to release-2023-06-07_23-01 (#3407)
# Motivation
We would like to update our dependencies on the IC repository.

Updating all dependencies at once causes too many changes, so this is
done piecemeal.

# Changes
## Resolver
```
0.271 warning: some crates are on edition 2021 which defaults to `resolver = "2"`, but virtual workspaces default to `resolver = "1"`                                                                                                                                                                                                                                                                                                                                                                                                                                          
0.271 note: to keep the current resolver, specify `workspace.resolver = "1"` in the workspace root's manifest                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
0.271 note: to use the edition 2021 resolver, specify `workspace.resolver = "2"` in the workspace root's manifest 
...
66.97 error[E0432]: unresolved import `crate::sys::IoSourceState`
```
Addresed by:
```
 [workspace]
+resolver = "2"
```
## Update IC commit
Update the `IC` repo commit used in the `sns_aggregator` `Cargo.toml` to
the latest release that works without any further code changes.

# Tests
See CI.

# Todos

- [x] Add entry to changelog (if necessary).

---------

Co-authored-by: Max Murphy <max@winning.black>