Fix IC cargo dependencies (#5282)
# Motivation

Updating the IC cargo dependencies has been failing:

https://github.com/dfinity/nns-dapp/actions/workflows/update-ic-cargo-deps.yaml

https://github.com/dfinity/nns-dapp/actions/runs/10244577609/job/28337826321
```
error: failed to select a version for `num-bigint`.
    ... required by package `icrc-ledger-types v0.1.6 (https://github.com/dfinity/ic?rev=release-2024-08-02_01-30-base#3d0b3f10)`
    ... which satisfies git dependency `icrc-ledger-types` of package `cycles-minting-canister v0.9.0 (https://github.com/dfinity/ic?rev=release-2024-08-02_01-30-base#3d0b3f10)`
    ... which satisfies git dependency `cycles-minting-canister` of package `nns-dapp v2.0.85 (/home/runner/work/nns-dapp/nns-dapp/rs/backend)`
versions that meet the requirements `^0.4.6` are: 0.4.6

all possible versions conflict with previously selected packages.

  previously selected package `num-bigint v0.4.5`
    ... which satisfies dependency `num-bigint = "^0.4"` (locked to 0.4.5) of package `candid v0.10.9`
    ... which satisfies dependency `candid = "^0.10.9"` (locked to 0.10.9) of package `nns-dapp v2.0.85 (/home/runner/work/nns-dapp/nns-dapp/rs/backend)`

failed to select a version for `num-bigint` which could resolve this conflict
```

The `num-bigint` issue goes away after deleting the `Cargo.lock` file
but then another issue appears:
```
$ rm Cargo.lock
$ scripts/update-ic-cargo-deps --ref "release-2024-08-02_01-30-base"
Updating Cargo.toml, changing 'release-2024-08-02_01-30-base' to 'release-2024-08-02_01-30-base'.
    Updating crates.io index
    Updating git repository `https://github.com/dfinity/ic`
    Updating git repository `https://github.com/dfinity/cdk-rs`
    Updating git repository `https://github.com/dfinity-lab/build-info`
error: failed to select a version for the requirement `ic_bls12_381 = "=0.9.2"`
candidate versions found which didn't match: 0.10.0, 0.9.1, 0.9.0, ...
location searched: crates.io index
required by package `ic-crypto-internal-bls12-381-type v0.9.0 (https://github.com/dfinity/ic?rev=release-2024-08-02_01-30-base#3d0b3f10)`
    ... which satisfies git dependency `ic-crypto-internal-bls12-381-type` of package `ic-crypto-internal-multi-sig-bls12381 v0.9.0 (https://github.com/dfinity/ic?rev=release-2024-08-02_01-30-base#3d0b3f10)`
    ... which satisfies git dependency `ic-crypto-internal-multi-sig-bls12381` of package `ic-crypto-node-key-validation v0.9.0 (https://github.com/dfinity/ic?rev=release-2024-08-02_01-30-base#3d0b3f10)`
    ... which satisfies git dependency `ic-crypto-node-key-validation` of package `registry-canister v0.9.0 (https://github.com/dfinity/ic?rev=release-2024-08-02_01-30-base#3d0b3f10)`
    ... which satisfies git dependency `registry-canister` of package `ic-nns-governance v0.9.0 (https://github.com/dfinity/ic?rev=release-2024-08-02_01-30-base#3d0b3f10)`
    ... which satisfies git dependency `ic-nns-governance` of package `nns-dapp v2.0.84 (/Users/dskloet/dev/nns-dapp/tree8/rs/backend)`
```

This happens because the IC repo depends on version 0.9.2 of
ic_bls12_381, but [this version was
yanked](https://crates.io/crates/ic_bls12_381/versions) so NNS dapp is
unable to depend on it.

It seems that IC can still depend on it because it [already had the
entry](https://github.com/dfinity/ic/blob/54a37653eb61174bbcba44fa8ad42ed03ce672cf/Cargo.lock#L12855-L12868)
in its `Cargo.lock` file so the work-around for now is to add the same
entry in the NNS dapp `Cargo.lock` file.

We expect the IC repo to update its dependency soon:
https://dfinity.slack.com/archives/CH07MRJQ7/p1722933995226969

After this, `scripts/update-ic-cargo-deps --ref
"release-2024-08-02_01-30-base"` which runs `cargo update --workspace`
passed, but `cargo build` still
[fails](https://github.com/dfinity/nns-dapp/actions/runs/10263507749/job/28395518922?pr=5282)
with:
```
error[E0277]: the trait bound `Arc<std::vec::Vec<u8>>: _::_serde::Serialize` is not satisfied
#32 77.17     --> /opt/cargo/git/checkouts/ic-ca00ee28655ee32e/3d0b3f1/rs/types/types/src/consensus/idkg/schnorr.rs:204:38
#32 77.17      |
#32 77.17 204  | #[derive(Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
#32 77.17      |                                      ^^^^^^^^^ the trait `_::_serde::Serialize` is not implemented for `Arc<std::vec::Vec<u8>>`
#32 77.17 ...
#32 77.17 208  |     pub message: Arc<Vec<u8>>,
#32 77.17      |     --- required by a bound introduced by this call
#32 77.17      |
#32 77.17      = note: for local types consider adding `#[derive(serde::Serialize)]` to your `Arc<std::vec::Vec<u8>>` type
#32 77.17      = note: for types from other crates check whether the crate offers a `serde` feature flag
#32 77.17      = help: the following other types implement trait `_::_serde::Serialize`:
#32 77.17                &'a T
#32 77.17                &'a mut T
#32 77.17                ()
#32 77.17                (T,)
#32 77.17                (T0, T1)
#32 77.17                (T0, T1, T2)
#32 77.17                (T0, T1, T2, T3)
#32 77.17                (T0, T1, T2, T3, T4)
#32 77.17              and 606 others
#32 77.17 note: required by a bound in `_::_serde::ser::SerializeStruct::serialize_field`
#32 77.17     --> /opt/cargo/registry/src/index.crates.io-6f17d22bba15001f/serde-1.0.204/src/ser/mod.rs:1867:21
#32 77.17      |
#32 77.17 1865 |     fn serialize_field<T>(&mut self, key: &'static str, value: &T) -> Result<(), Self::Error>
#32 77.17      |        --------------- required by a bound in this associated function
#32 77.17 1866 |     where
#32 77.17 1867 |         T: ?Sized + Serialize;
#32 77.17      |                     ^^^^^^^^^ required by this bound in `SerializeStruct::serialize_field`
#32 77.17      = note: this error originates in the derive macro `Serialize` (in Nightly builds, run with -Z macro-backtrace for more info)
#32 77.17 
```
etc.

This was caused by https://github.com/dfinity/ic/pull/344 and the fix
for this is in
https://github.com/dfinity/ic/commit/799cf9f94c0fbaeae9c328f64da03640d37b0480
but that's not yet part of a release so we use that rev directly.

# Changes

1. Replace the entire `Cargo.lock` file with just
```
[[package]]
name = "ic_bls12_381"
version = "0.9.2"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "3fb94c398e5a5bc56a8f0ff995b2679829e2bbc5f145d9c3ea58d303036e05f2"
dependencies = [
 "digest",
 "ff",
 "group",
 "pairing",
 "rand_core",
 "subtle",
 "zeroize",
]
```
2. Run `scripts/update-ic-cargo-deps --ref
799cf9f94c0fbaeae9c328f64da03640d37b0480`

# Tests

Dependencies are updated and CI passes.

# Todos

- [ ] Add entry to changelog (if necessary).
not necessary