Remove useless test (#5653)
# Motivation

`frontend/src/tests/routes/app/home/home-page.spec.ts` was introduced in
https://github.com/dfinity/nns-dapp/pull/3985 to test that with
different feature flag different components were rendered on the route.
But the feature flag was cleaned up and now the test doesn't really test
anything.
There also isn't anything to test because [the
page](https://github.com/dfinity/nns-dapp/blob/470fdb75ab141f8f49a2bfb61d25c4e5ef88ff7e/frontend/src/routes/(app)/(home)/%2Bpage.svelte)
just renders a single component without any logic.

Additionally, rendering the component results in unmocked API functions
being called, which can cause problems.
In particular when trying to update the vitest dependency, this happens
to result in errors being logged:
```
TypeError: Cannot read properties of undefined (reading 'httpDetails')
    at caller (/Users/dskloet/dev/nns-dapp/tree1/frontend/node_modules/@dfinity/agent/src/actor.ts:508:41)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Module.queryIcrcToken (/Users/dskloet/dev/nns-dapp/tree1/frontend/src/lib/api/icrc-ledger.api.ts:41:21)
    at Module.queryAndUpdate (/Users/dskloet/dev/nns-dapp/tree1/frontend/src/lib/services/utils.services.ts:108:3)
    at async Promise.all (index 0)
```

# Changes

Remove `frontend/src/tests/routes/app/home/home-page.spec.ts`.

# Tests

not tested

# Todos

- [ ] Add entry to changelog (if necessary).
not necessary