Update IC cargo deps (#5079)
# Motivation

We have a GitHub workflow to do this but it [has been
failing](https://github.com/dfinity/nns-dapp/actions/workflows/update-ic-cargo-deps.yaml).
Turns out I didn't know which Slack channel the failure notifications
were sent to.

The reason it was failing is that `serde` and `serde_bytes` required a
newer version in the IC repo than in nns-dapp.
`serde` was actually updated just recently.

Even then updating the deps had some issues:
```
$ scripts/update-ic-cargo-deps --ref 163d59558fcbb4531d3acd8ad85ca1af849f2581
Updating Cargo.toml, changing 'release-2024-05-29_23-02-base' to '163d59558fcbb4531d3acd8ad85ca1af849f2581'.
    Updating git repository `https://github.com/dfinity/ic`
    Updating crates.io index
error: failed to select a version for `tempfile`.
    ... required by package `ic-icrc1 v0.9.0 (https://github.com/dfinity/ic?rev=163d59558fcbb4531d3acd8ad85ca1af849f2581#163d5955)`
    ... which satisfies git dependency `ic-icrc1` of package `ic-icrc1-index-ng v0.9.0 (https://github.com/dfinity/ic?rev=163d59558fcbb4531d3acd8ad85ca1af849f2581#163d5955)`
    ... which satisfies git dependency `ic-icrc1-index-ng` of package `ic-sns-init v0.9.0 (https://github.com/dfinity/ic?rev=163d59558fcbb4531d3acd8ad85ca1af849f2581#163d5955)`
    ... which satisfies git dependency `ic-sns-init` of package `ic-nns-governance v0.9.0 (https://github.com/dfinity/ic?rev=163d59558fcbb4531d3acd8ad85ca1af849f2581#163d5955)`
    ... which satisfies git dependency `ic-nns-governance` of package `nns-dapp v2.0.80 (/Users/dskloet/dev/nns-dapp/tree3/rs/backend)`
versions that meet the requirements `^3.10.1` are: 3.10.1

all possible versions conflict with previously selected packages.

  previously selected package `tempfile v3.6.0`
    ... which satisfies dependency `tempfile = "^3.0"` (locked to 3.6.0) of package `proptest v1.4.0`
    ... which satisfies dependency `proptest = "^1.0.0"` (locked to 1.4.0) of package `nns-dapp v2.0.80 (/Users/dskloet/dev/nns-dapp/tree3/rs/backend)`

failed to select a version for `tempfile` which could resolve this conflict
```

But this went away if I delete `Cargo.lock` first and run `cargo update`
later.

I used the
[commit](https://github.com/dfinity/ic/commit/163d59558fcbb4531d3acd8ad85ca1af849f2581)
that updates `curve25519-dalek` as the `ref` because it hasn't yet been
included in a named release.

# Changes

1. Updated serde_bytes from 0.11.12 to 0.11.14.
2. Deleted `Cargo.lock`
3. Ran `scripts/update-ic-cargo-deps --ref
163d59558fcbb4531d3acd8ad85ca1af849f2581`
4. Restored `Cargo.lock`
5. Ran `cargo update`

# Tests

`cargo audit` passes with
```
Crate:     serde_cbor
Version:   0.11.2
Warning:   unmaintained
Title:     serde_cbor is unmaintained
Date:      2021-08-15
ID:        RUSTSEC-2021-0127
URL:       https://rustsec.org/advisories/RUSTSEC-2021-0127
Dependency tree:
serde_cbor 0.11.2
├─...
...

warning: 1 allowed warning found
```

# Todos

- [ ] Add entry to changelog (if necessary).
not necessary