Update README to reflect the need to install docker-buildx (#2063)
# Motivation

A user could not build the Wasm image with `scripts/docker-build`, the
command resulted in the following error
```sh
ERROR: BuildKit is enabled but the buildx component is missing or broken.
       Install the buildx component to build images with BuildKit:
       https://docs.docker.com/go/buildx/
```

# Changes

Added the steps necessary to install `docker-buildx`