feat: Remove SnsAggregator.stable_data as the function is broken in production and no longer used in testing (#7295)
# Motivation

```
dfx canister --ic call 3r4gx-wqaaa-aaaaq-aaaia-cai stable_data
Error: Failed query call.
Caused by: The replica returned a rejection error: reject code CanisterError, reject message Error from Canister 3r4gx-wqaaa-aaaaq-aaaia-cai: Canister exceeded the limit of 5000000000 instructions for single message execution..
Try optimizing this method to consume fewer instructions or split the work across multiple messages. See documentation: https://internetcomputer.org/docs/current/references/execution-errors#instruction-limit-exceeded, error code Some("IC0522")
```

# Changes

Remove the endpoint (technically, a breaking change) and remove the
scripts/sns/aggregator/get_stable_data file.

# Tests

Let's see what the CI has to say.

# Todos

- [ ] Changelog